### ISSUE TITLE
フレームワークの選定

### ISSUE THREAD

**Issue by eteeeeeerminal** [VirtualProgrammersNetwork/vpn-website#1]
website製作に使うフレームワークについて議論しましょう。

要件は以下の2つくらいあればよさそう

要件
- markdown等の簡単な形式で、各自がプロフィールページを記述できる。
- 各自が記述したプロフィールページの情報から、要約を生成して、一覧で表示できるようにする。

**Comment by neverclear86** [comment]
Markdown使うのと、私の宗教的理由でNode.jsがいいです
フロントはVueに1票

**Comment by kurone-kito** [comment]
一行目は全面同意ですが、私は React 宗派ですね。。😌

**Comment by eteeeeeerminal** [comment]
メインで開発する人に合わせるのがいいんですかね？

私はそんなにゴリゴリ書ける分けじゃないので決定は任せます。

**Comment by kurone-kito** [comment]
#3 のたたき台をマージしましたので、一旦解決したと見て close します😌
