### ISSUE TITLE
ライセンス・リポジトリに含めるリソースについて

### ISSUE THREAD

**Issue by eteeeeeerminal** [VirtualProgrammersNetwork/vpn-website#2]
ロゴ、アイコン、立ち絵画像等をリポジトリに含めると、ライセンスが難しくなりそう。

立ち絵等にライセンスが付けられない場合があります。
(アバターを外注している人もいるので)

なので、ウェブサイトに含まれる画像データ等について、どのように扱うか、早めに決めたいです。

対策としては、
- 画像を別の場所に置く
- 画像にはライセンスを適用しないと明記する
等ですかね。

**Comment by KasuyaMofu** [comment]
- 画像も含め、コードは全てNo Lisence（各人に帰属する）にする
  - 利用するフレームワークは別途ライセンス表示する
- サイトを構成するコード、画像等のリソースを保管するリポジトリは別に分ける

ビルドする際の問題だと思うので、リポジトリで何を作るかは明確にしたいですね

**Comment by eteeeeeerminal** [comment]
画像類は、別のリポジトリに置いた方がスッキリしますかね

**Comment by eteeeeeerminal** [comment]
画像用のリポジトリを別に作って、ビルド時にクローンしてくる方向で考えてます。

他にいい方法とか定番の方法があればDisucussions #7  で雑に意見ください。

**Comment by eteeeeeerminal** [comment]
とりあえずリポジトリを作った。

https://github.com/VirtualProgrammersNetwork/vpn-website-resource

**Comment by eteeeeeerminal** [comment]
別のリポジトリに置く方法について

Next.jsの仕様上静的リソースはすべて、public下に置かないといけなくて、これは変更できない。
https://nextjs.org/docs/basic-features/static-file-serving

暫定のゴリ押し解決策として、 `package.json` に以下のスクリプトを書いてビルド時にも実行させる。
もっと賢いやり方が見つかるまでこの方法を採用します。
```
"scripts": {
  ...
  "rsrc:clone": "git clone https://github.com/VirtualProgrammersNetwork/vpn-website-resource.git && cp vpn-website-resource/public .",
}
```

この方法だと、クローン元のリポジトリとの同期が問題になる場合がありそう。
git submoduleの使用も検討する
(使ったことないので調べてみる。特に、licenseの扱い要確認)

**Comment by eteeeeeerminal** [comment]
別の案として、他のサイトに置いてURLで参照する方法がある。
もちろんできるが、その場合`next.config.js`にドメインを書かなければいけなくなる。

```
module.exports = {
  images: {
    domains: ['hogehoge.com'],
  },
};
```

サイトが1つや2つなら全然大丈夫だけど、
全員が別々のサイトを使ったりすると不格好になる気がする。

手間がかかるのでできれば1つ目の別リポジトリにまとめる方法でいきたい。
