### ISSUE TITLE
mainブランチで作業したい

### ISSUE THREAD

**Issue by KasuyaMofu** [VirtualProgrammersNetwork/vpn-website#22]
このような軽微な変更をPR形式で入れてると大変なので、mainブランチで作業したい。心理的な障壁も小さくなると思う

- https://github.com/VirtualProgrammersNetwork/vpn-website/pull/21

**Comment by eteeeeeerminal** [comment]
確かに、、、`member-data.yaml`の編集だったら、直接mainにpushしても問題なさそう
あと、vpn-website-resourceに画像追加するのも、衝突起こりそうにないし、直接mainでもいいかも
read meに`member-data.yaml`の編集くらいだったら直接mainに出していいように書きますか。
